// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function evenFibboSum(n) {
  let a = 1;
  let b = 2;
  let c = a + b;
  let sum = 2;
  while (c < n) {
    c = a + b;
    a = b;
    b = c;
    if (c % 2 === 0) {
      sum += c;
    }
  }
  return sum;
}

// answer: 4613732